[package]
name = "ch10_02_patterns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ch10_01_enums = {path = "../ch10_01_enums"}