[workspace]
members = [
    "ch11_01_using_traits",
    "ch11_02_trait_object",
    "ch11_03_generic_functions_and_type_parameters",
    "ch11_04_defining_and_implementing_traits",
    "ch11_05_full_qualified_method_calls",
    "ch11_06_trait_define_relationship_btween_types"
]