[package]
name = "net_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustdns = "0.4"
ipinfo = "0.5"
serde_json = "1"
surf = "1"
async-std = { version = "1.12.0", features = ["attributes", "unstable"] }