[package]
name = "ch19_concurrency"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.6.0"
time = { version = "0.3", features = ["macros"] }
lazy_static = { version = "1.4.0" }